remote_theme: giellalt/jekyll-theme-giellalt@main
title: Shared Multilingual Names
description: Shared Multilingual lexical and other resources for use across GiellaLT language models
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jemoji

defaults:
  - scope: { path: "" }
    values:
      layout: default

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
